/*
    This header file is generated by sotom at 2022-07-24 02:28:38.722482
    visit sotom at https://github.com/sislamrafi/sotom
*/

#ifndef __LIBS__PWM_H__
#define __LIBS__PWM_H__

//define all your function prototypes and variables under this line
#include "../../main/board.h"
#include "../../libs/TIMER/timer.h"

void ConfigTimer1ForPWM(void);
void ConfigTimer2ForPWM(void);
void setTimer2PWMDutyCycle(uint16_t duty);

#endif
